# Gerado pelo install.sh — paleta: Azul escuro
background                #0b1220
foreground                #dbeafe
selection_background      #1e3a5f
selection_foreground      #eff6ff
url_color                 #60a5fa
cursor                    #93c5fd
cursor_text_color         #0b1220
active_border_color       #2563eb
inactive_border_color     #172554
bell_border_color         #f87171
visual_bell_color         none
active_tab_background     #172554
active_tab_foreground     #eff6ff
inactive_tab_background   #0f1b31
inactive_tab_foreground   #93a4bd
tab_bar_background        none
tab_bar_margin_color      none
color0                    #0b1220
color1                    #ef4444
color2                    #22c55e
color3                    #f59e0b
color4                    #3b82f6
color5                    #a855f7
color6                    #06b6d4
color7                    #dbeafe
color8                    #475569
color9                    #f87171
color10                   #4ade80
color11                   #fbbf24
color12                   #60a5fa
color13                   #c084fc
color14                   #22d3ee
color15                   #f8fafc
