# Gerado pelo install.sh — paleta: Tenta acreditar
background                #15171a
foreground                #e6e6e6
selection_background      #34383f
selection_foreground      #e6e6e6
cursor                    #ffffff
cursor_text_color         #15171a
url_color                 #7fe8d2
active_border_color       #4b5563
inactive_border_color     #34383f
bell_border_color         #f7768e
visual_bell_color         none
active_tab_background     #34383f
active_tab_foreground     #e6e6e6
inactive_tab_background   #15171a
inactive_tab_foreground   #414868
tab_bar_background        none
tab_bar_margin_color      none
color0                    #15171a
color1                    #f7768e
color2                    #9ece6a
color3                    #e0af68
color4                    #7aa2f7
color5                    #bb9af7
color6                    #73daca
color7                    #e6e6e6
color8                    #414868
color9                    #ff899d
color10                   #a9dc76
color11                   #e9c46a
color12                   #8db0ff
color13                   #c7a0ff
color14                   #7fe8d2
color15                   #ffffff
