-- GERADO a partir de vim/config/themes.vim (os mesmos temas do Vim).
-- Para criar/renomear temas SEM mexer aqui, use lua/icaro/themes_local.lua (veja o .example).
return {
  { id = "maria_isabel", title = "Maria Isabel", short = "MI", subtitle = "Pensão de Pet" },
  { id = "jales", title = "Jales", short = "JAL", subtitle = "Pensão de Pet" },
  { id = "camelo", title = "Camelo", short = "CAM", subtitle = "Pensão de Pet" },
  { id = "sassa", title = "Iogurte", short = "ELA", subtitle = "Antiresenha+" },
  { id = "malvadao", title = "Malvadão", short = "MAL", subtitle = "Pensão de Pet" },
  { id = "mateus_sao_paulino", title = "Mateus São Paulino", short = "MSP", subtitle = "Pensão de Pet" },
  { id = "pedro_de", title = "Pedro de...", short = "PED", subtitle = "Pensão de Pet, cor : Clara" },
  { id = "belchior", title = "Belchior", short = "BEL", subtitle = "Pensão de Pet" },
  { id = "lucas_ribeiro", title = "Lucas Ribeiro?", short = "LUC", subtitle = "Pensão de Pet" },
  { id = "alan_turing", title = "Alan Turing", short = "AT", subtitle = "Pensão de Pet" },
  { id = "alan_turing_antiresenha", title = "Alan Turing", short = "AT", subtitle = "Antiresenha" },
  { id = "henrique", title = "Henrique", short = "HEN", subtitle = "Pensão de Pet" },
  { id = "off_light", title = "Of(f) Light", short = "OFF", subtitle = "Pensão de Pet" },
  { id = "geraldo", title = "Geraldo", short = "GER", subtitle = "Pensão de Pet" },
  { id = "cabeludo", title = "Cabeludo", short = "CAB", subtitle = "Antiresenha" },
  { id = "cookie", title = "Cookie", short = "CK", subtitle = "Antiresenha" },
  { id = "ruiva", title = "Ruiva", short = "RUI", subtitle = "Antiresenha" },
  { id = "baiana", title = "Baiana", short = "BAI", subtitle = "Antiresenha" },
  { id = "do_mal", title = "Do Mal", short = "DM", subtitle = "Antagonista" },
  { id = "sofia", title = "Paz", short = "PAZ", subtitle = "Antiresenha" },
  { id = "guerra", title = "Guerra", short = "WAR", subtitle = "Antiresenha+" },
  { id = "soares", title = "Soares", short = "SOA", subtitle = "Pensão de Pet+" },
  { id = "biscoitinho", title = "Biscoitinho", short = "BIS", subtitle = "Antagonista" },
  { id = "gvsl", title = "GVSL", short = "GVS", subtitle = "Antagonista" },
  { id = "jf", title = "JF", short = "JF", subtitle = "GOATS" },
  { id = "toyman", title = "ToyMan", short = "TOY", subtitle = "Antagonista" },
  { id = "massoni", title = "Massoni", short = "MAS", subtitle = "GOATS" },
  { id = "dijkstra", title = "Dijkstra", short = "DIJ", subtitle = "Como é que se escreve Dijkstra?" },
  { id = "ever_dream_this_man", title = "Ever Dream This Man?", short = "EDM", subtitle = "" },
  { id = "raul", title = "Raul", short = "RAU", subtitle = "Pensão de Pet" },
  { id = "acesso_negado", title = "ACESSO NEGADO", short = "NEG", subtitle = "" },
  { id = "espresso", title = "De cujos", short = "CUJ", subtitle = "Antagonistas" },
  { id = "plum", title = "Titio", short = "TIT", subtitle = "Goats" },
  { id = "flatui", title = "Animes", short = "ANI", subtitle = "Antagonistas" },
  { id = "neocybervim", title = "Cavaleiro do apocalipse", short = "CAV", subtitle = "Antagonistas" },
  { id = "sunbather", title = "Guardians", short = "GUA", subtitle = "Antagonistas" },
  { id = "tatami", title = "Shampoo de...", short = "SHA", subtitle = "Antagonistas" },
  { id = "lucid", title = "Cuti Cuti", short = "CUT", subtitle = "Goats" },
  { id = "lucario", title = "Eurico", short = "EUR", subtitle = "Goats" },
  { id = "roti", title = "Do bem", short = "BEM", subtitle = "Pensão de Pet+" },
  { id = "hotdog", title = "Héctor", short = "HEC", subtitle = "Pensão de Pet comunista" },
  { id = "macvim_light", title = "JA", short = "JA", subtitle = "Goats" },
  { id = "farout", title = "Holanda", short = "HOL", subtitle = "Goats" },
  { id = "burgundy", title = "Ela também é maligna...", short = "MAL2", subtitle = "Antagonistas" },
  { id = "petra", title = "Sonhei com você essa noite", short = "SON", subtitle = "Não tenho descrição para isso" },
}
